- module: oracle
  period: 30s
  metricsets:
    - session
  hosts:
    - "oracle://system:oracle@localhost:1521/XE"

- module: oracle
  period: 1m
  metricsets:
    - osstats
    - sgastats
    - sqlstats
    - sysmetric
    - sessmetric
    - tablespace
    - recoveryarea
  hosts:
    - "oracle://system:oracle@localhost:1521/XE"

- module: oracle
  period: 30m
  metricsets:
    - rmanjobs
  hosts:
    - "oracle://system:oracle@localhost:1521/XE"

## Example RAC configuration for Instance specific metrics
#- module: oracle
#  period: 1m
#  metricsets:
#    - alertlog
#    - recoveryarea
#  hosts:
#    - "oracle://system:oracle@host1:1521/XE1"
#    - "oracle://system:oracle@host2:1521/XE2"
#
