FROM oracle/database:11.2.0.2-xe

# set default password for SYS, SYSTEM ane PDBADMIN
ENV ORACLE_PWD=Login4Me

# expose only listener port
EXPOSE 1521

RUN --memory-swap=-1

# overriding healtcheck
HEALTHCHECK --interval=5s --retries=60 --start-period=30s CMD test `netstat -tulpen | grep 0.0.0.0:1521 | wc -l` -eq 1
