FROM oracle/database:12.2.0.1-ee

# set default password for SYS, SYSTEM ane PDBADMIN
ENV ORACLE_PWD=Login4Me

# expose only listener port
EXPOSE 1521

# overriding healtcheck
HEALTHCHECK --interval=5s --retries=60 --start-period=30s CMD /opt/oracle/checkDBStatus.sh > /dev/null || exit 1
