sudo: required
dist: trusty

services:
  - docker

language: go

env:
  global:
    - GO_VERSION="$(cat .go-version)"
    - GOX_FLAGS="-arch amd64"
    - ORACLE_COOKIE=ic_linuxx8664
    - ORACLE_DOWNLOAD_DIR=.cache/oracle
    - secure: LAoqEJoSCF8cF4FVIuv1d7onAcGz3qZVFO79Vnyn4dJrprAln+9uBGKn2oIsHwdHWKgg+jQW5vrKrP6RAnRAPgJDsFLR5MXPlf2xnz5LMNWSFsyNOGL4kboNcpXEiYY8sSiMrTRJx2RacLIF+LuknfJ16SVIYF0lQcUEho0IxBtqkuXyT+xiPa+oVdakhGKRWRyXWzXBq6EfDnmPMqpwqMEJQbilYF0cQD0kAyQsWHxiapkcw/OMP37hweat8vPmeHklxGIATh4aLMQcRZntCaWTpEhmHeKMQz81e36GKYDdssD3K/vrtHf+oNd/nHvjfp5en/hW82Y8oUzkjM2FcpexXgAsl0e8pttN5QFlHhq1TAueK1uuaoCvWtQ2QXvWWZgcOORrE1+lXCUKWGAQSqCeM3wEUzPd2Sv8VOFJGIF56BWwSfQG55u3PDMb5jUjuOCcwHs7dAf5njnUpjtWUOwrnrbHwz2y+OSl3yqBHD5821xnXqq/wov7mwU/6YKjGRTmUlsfNVIyOHDUlAkXG20Y4jQm4qBBvTjwwR9z6Vb7Y5WAxK7jZv8dEPmYle+rXJVxJXBSKZocd2A/VKD4v1DqY5L2SFiNsV0y/VSB9vEhGWbTGMaUf3EMsYuzvBqjCJKKVW181xFjWdGYGTYc4ojsP2UMONkAOucJEkDZ0j4=
    - secure: AbOQx25Lghjna2KFlw9yjzSjt4ez5/6Lr9YZ4LNEAY+pYcFJQYasD6o6d7APoa7fHFFjL5PjU04TjMiFF5FCgcitoYC7ERCr0W+VBQBIRPGadsJOPQavz13CEDrTVUD6sdIh5yi2aGSkQxDOxN/zrsa6xda/8J16KSaNO99zLasmlZuB5sWnvPRbbaY/UqoEM1NWMd030rPQb0Tgt5FBU52pQhJNjxfu/lgHW5qnrQ979gJ6lYEH9XWpcLPX5+65U8XMwA/ubzPdGYzs3Cl2hfx5h0pu1FA51FcnyeBJAgQspO2LfQuVPQiQyDvNRUPgt3U6OVakTavk4YEfR/biKR53b6U0iRxvu0f792TdC6yjsSkr6WkVfd26KwIgFC0J2Lnqj9UfPE3aRV/FMDjSpZP+iKXUkDt4ALzYo/FoC244rEFjg9pq7OGYHlh/aH9wySwkCI9ObvX+hpvlvz7fFUpEn0yQYvQ0yYfnrOJ2lK4TapdfOGUE+l6RvFbEw5XXnzlFMWyfeM4SV6gwkBFXUgeWGaa48BURX05LguYjOz5UO1rP6QvgJBP8nCOKMfAhD1tIcKReNbnl6KUN5/9PdKnLdQ1d/N6f3HWnsnhio0Q1SGmLNG0Sr+/CbB7sgcs0qsGXmQB8FbvnVC6WQTkU7Gmelw6zPHvhK4daiWNz8cg=

jobs:
  include:
    # Prepare Oracle Database Docker Image
    #- os: linux
    #  env:
    #    - TARGET="MODULE=oracle PORT=1521 make run-module"
    #  go: $GO_VERSION
    #  install:
    #    - make python-env
    #    - source $GOPATH/src/github.com/mguggi/oraclebeat/build/python-env/bin/activate
    #  stage: prepare

    # Oraclebeat
    - os: linux
      env:
        - ORACLE_FILE="instantclient/122010/oracle-instantclient12.2-basic-12.2.0.1.0-1.x86_64.rpm"
        - LD_LIBRARY_PATH="/usr/lib/oracle/12.2/client64/lib"
        - TARGET="test-oraclebeat"
      go: $GO_VERSION
      install:
        - .travis/oracle/download.sh
        - sudo apt-get -qq install libaio1 rpm
        - sudo rpm --install --nodeps $ORACLE_DOWNLOAD_DIR/oracle-instantclient12.2-*.rpm
      stage: test

before_install:
  - umask 022
  - go get github.com/pkg/errors
  - go get github.com/stretchr/testify/assert
  - go get github.com/docker/libcompose/docker
  - chmod -R go-w $TRAVIS_BUILD_DIR

install: true

script:
  - make $TARGET

after_success:
  # Copy full.cov to coverage.txt because codecov.io requires this file
  - bash <(curl -s https://codecov.io/bash) -f build/coverage/unit.cov
