########################## Metricbeat Configuration ###########################

# This file is a full configuration example documenting all non-deprecated
# options in comments. For a shorter configuration example, that contains only
# the most common options, please see metricbeat.yml in the same directory.
#
# You can find the full configuration reference here:
# https://www.elastic.co/guide/en/beats/metricbeat/index.html

#============================  Config Reloading ===============================

# Config reloading allows to dynamically load modules. Each file which is
# monitored must contain one or multiple modules as a list.
metricbeat.config.modules:

  # Glob pattern for configuration reloading
  path: ${path.config}/conf.d/*.yml

  # Period on which files under path should be checked for changes
  reload.period: 10s

  # Set to true to enable config reloading
  reload.enabled: false

# Maximum amount of time to randomly delay the start of a metricset. Use 0 to
# disable startup delay.
metricbeat.max_start_delay: 10s

#============================== Autodiscover ===================================

# Autodiscover allows you to detect changes in the system and spawn new modules
# as they happen.

#metricbeat.autodiscover:
  # List of enabled autodiscover providers
#  providers:
#    - type: docker
#      templates:
#        - condition:
#            equals.docker.container.image: etcd
#          config:
#            - module: etcd
#              metricsets: ["leader", "self", "store"]
#              period: 10s
#              hosts: ["${host}:2379"]

#==========================  Modules configuration ============================
oraclebeat.modules:

#---------------------------- Oracle Module Module ---------------------------
- module: oracle
  period: 30s
  metricsets:
    - session
    - sgastats

  # List of Oracle connection strings
  hosts: ["oracle://system:Login4Me@localhost:1521/XE"]

- module: oracle
  period: 1m
  metricsets:
    - osstats
    - sqlstats
    - sysmetric
    - sessmetric
    - tablespace
    - recoveryarea

  # List of Oracle connection strings
  hosts: ["oracle://system:Login4Me@localhost:1521/XE"]

- module: oracle
  period: 1h
  metricsets:
    - rmanjobs

  # List of Oracle connection strings
  hosts: ["oracle://system:Login4Me@localhost:1521/XE"]


